const subjects=[['🐍','Python','Programming fundamentals, automation and security scripting.'],['☕','Java','Object-oriented programming and application development.'],['🌐','HTML','Web page structure, semantic elements and forms.'],['🎨','CSS','Layouts, responsive design, styling and animations.'],['⚡','JavaScript','DOM, events, functions and interactive web apps.'],['🗄️','SQL','Queries, tables, joins and relational databases.'],['🛡️','Cybersecurity','Security fundamentals, threats and safe defense concepts.'],['🤖','AI Basics','Core ideas behind artificial intelligence and machine learning.']];
const notes=[['HTML','Semantic HTML','Semantic elements describe the meaning of content. Examples include header, nav, main, section, article and footer.'],['CSS','Flexbox','Flexbox makes one-dimensional layouts easier. Use display:flex with justify-content and align-items to control alignment.'],['JavaScript','DOM','The Document Object Model represents a web page as objects that JavaScript can read and change.'],['JavaScript','Events','Events let a page react to actions such as clicks, typing and form submission.'],['SQL','JOIN','JOIN combines related rows from tables. Common types include INNER JOIN, LEFT JOIN, RIGHT JOIN and FULL JOIN.'],['Cybersecurity','CIA Triad','Confidentiality protects information from unauthorized access, integrity protects correctness, and availability keeps services accessible.'],['Python','Variables','A Python variable is a name that refers to a value. Python determines the value type at runtime.'],['AI','Machine Learning','Machine learning allows systems to learn patterns from data and use those patterns to make predictions or decisions.'],['Java','OOP','Object-oriented programming organizes software around objects and concepts such as classes, inheritance, encapsulation and polymorphism.']];
const subjectGrid=document.getElementById('subjectGrid');const notesGrid=document.getElementById('notesGrid');
function renderSubjects(filter=''){subjectGrid.innerHTML=subjects.filter(s=>s.join(' ').toLowerCase().includes(filter.toLowerCase())).map(s=>`<article class="subject-card"><div class="subject-icon">${s[0]}</div><h3>${s[1]}</h3><p>${s[2]}</p></article>`).join('')||'<p>No subjects found.</p>'}
function renderNotes(filter=''){notesGrid.innerHTML=notes.filter(n=>n.join(' ').toLowerCase().includes(filter.toLowerCase())).map(n=>`<article class="note-card"><small>${n[0]}</small><h3>${n[1]}</h3><p>${n[2]}</p></article>`).join('')||'<p>No notes found.</p>'}
renderSubjects();renderNotes();document.getElementById('noteSearch').addEventListener('input',e=>renderNotes(e.target.value));

const knowledge=[
[['python','variable'],'Python variables store references to values. Example: <code>name = "Alex"</code>. Common basics are numbers, strings, lists, dictionaries and booleans.'],
[['python','loop'],'A Python loop repeats work. <code>for</code> is useful for iterating over items, while <code>while</code> repeats while a condition remains true.'],
[['python','function'],'A Python function is a reusable block of code defined with <code>def</code>. Functions can accept parameters and return values.'],
[['html','html'],'HTML is the markup language used to structure web content. Learn headings, paragraphs, links, images, lists, forms and semantic elements.'],
[['dom','javascript'],'The DOM (Document Object Model) represents an HTML document as a tree of objects. JavaScript can select elements, change content and respond to events.'],
[['javascript','js'],'JavaScript adds behavior and interactivity to web pages. Learn variables, functions, arrays, objects, DOM manipulation, events and asynchronous code.'],
[['css','css'],'CSS controls how HTML looks. Important topics include selectors, box model, Flexbox, Grid, responsive design, transitions and animations.'],
[['sql','join'],'SQL JOINs combine data from related tables. INNER JOIN returns matching rows; LEFT JOIN keeps all rows from the left table plus matches from the right.'],
[['sql','sql'],'SQL is used to create, read, update and manage relational data. Start with SELECT, WHERE, ORDER BY, GROUP BY, INSERT, UPDATE, DELETE and JOIN.'],
[['cybersecurity','security'],'Cybersecurity protects systems, networks and data. Important foundations include authentication, access control, secure coding, networking, backups and incident response.'],
[['cia','triad'],'The CIA triad is a core security model: Confidentiality limits unauthorized access, Integrity protects data from improper change, and Availability keeps systems usable.'],
[['ai','artificial intelligence'],'Artificial intelligence is the field of building systems that perform tasks associated with human intelligence, such as recognizing patterns, understanding language and making predictions.'],
[['java','java'],'Java is a general-purpose, object-oriented programming language. Core topics include classes, objects, inheritance, interfaces, exceptions and collections.']
];
function answerFor(text){const q=text.toLowerCase();for(const [keys,answer] of knowledge){if(keys.some(k=>q.includes(k)))return answer}if(q.includes('hello')||q.includes('hi'))return 'Hello! 👋 Ask me about Python, Java, HTML, CSS, JavaScript, SQL, AI or cybersecurity.';if(q.includes('help'))return 'Try asking: “Explain Python variables”, “What is the DOM?”, “Explain SQL JOIN”, or “What is the CIA triad?”';return 'I can help with Python, Java, HTML, CSS, JavaScript, SQL, AI and cybersecurity. Try asking about a specific concept and I will explain it simply.'}
const chatBox=document.getElementById('chatBox');const chatInput=document.getElementById('chatInput');function addBubble(text,type){const d=document.createElement('div');d.className=`bubble ${type}`;d.innerHTML=type==='bot'?text.replace(/\n/g,'<br>'):escapeHtml(text);chatBox.appendChild(d);chatBox.scrollTop=chatBox.scrollHeight}
function escapeHtml(s){return s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
document.getElementById('chatForm').addEventListener('submit',e=>{e.preventDefault();const text=chatInput.value.trim();if(!text)return;addBubble(text,'user');chatInput.value='';setTimeout(()=>addBubble(answerFor(text),'bot'),250)});
document.querySelectorAll('[data-question]').forEach(b=>b.addEventListener('click',()=>{chatInput.value=b.dataset.question;chatInput.focus()}));
document.getElementById('clearChat').addEventListener('click',()=>{chatBox.innerHTML='<div class="bubble bot">Chat cleared. What would you like to study?</div>'});

const questions=[{q:'Which language is commonly used for web page behavior?',o:['HTML','CSS','JavaScript','SQL'],a:2},{q:'What does CSS mainly control?',o:['Database records','Web page presentation','Server hardware','Email accounts'],a:1},{q:'Which SQL command retrieves data?',o:['SELECT','PUSH','SHOWDATA','FETCHALL'],a:0},{q:'What does the C in the CIA triad stand for?',o:['Control','Confidentiality','Connection','Code'],a:1},{q:'Which Python keyword defines a function?',o:['func','define','def','function'],a:2}];let qi=0,score=0,selected=null;
function renderQuestion(){const x=questions[qi];selected=null;document.getElementById('quizProgress').textContent=`Question ${qi+1} of ${questions.length}`;document.getElementById('quizScore').textContent=`Score: ${score}`;document.getElementById('quizQuestion').textContent=x.q;document.getElementById('quizResult').textContent='';document.getElementById('quizOptions').innerHTML=x.o.map((o,i)=>`<button class="quiz-option" data-i="${i}">${o}</button>`).join('');document.querySelectorAll('.quiz-option').forEach(b=>b.addEventListener('click',()=>chooseAnswer(Number(b.dataset.i))))}
function chooseAnswer(i){if(selected!==null)return;selected=i;const x=questions[qi];document.querySelectorAll('.quiz-option').forEach((b,n)=>{b.disabled=true;if(n===x.a)b.classList.add('correct');if(n===i&&i!==x.a)b.classList.add('wrong')});if(i===x.a)score++;document.getElementById('quizScore').textContent=`Score: ${score}`;document.getElementById('quizResult').textContent=i===x.a?'Correct! 🎉':'Not quite — review the topic and try again.'}
document.getElementById('nextBtn').addEventListener('click',()=>{if(selected===null){document.getElementById('quizResult').textContent='Choose an answer first.';return}if(qi<questions.length-1){qi++;renderQuestion()}else{document.getElementById('quizResult').textContent=`Quiz complete! You scored ${score}/${questions.length}.`;qi=0;score=0;document.getElementById('nextBtn').textContent='Restart Quiz'}});renderQuestion();

const menuBtn=document.getElementById('menuBtn'),navLinks=document.getElementById('navLinks');menuBtn.addEventListener('click',()=>navLinks.classList.toggle('open'));navLinks.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>navLinks.classList.remove('open')));
const themeBtn=document.getElementById('themeBtn');if(localStorage.getItem('study_theme')==='light')document.body.classList.add('light');function updateThemeIcon(){themeBtn.textContent=document.body.classList.contains('light')?'☀':'☾'}updateThemeIcon();themeBtn.addEventListener('click',()=>{document.body.classList.toggle('light');localStorage.setItem('study_theme',document.body.classList.contains('light')?'light':'dark');updateThemeIcon()});document.getElementById('year').textContent=new Date().getFullYear();
